from app.repositories.enrollment_repository import EnrollmentRepository
from app.models.enrollment import Enrollment
from app.repositories.course_repository import CourseRepository
class EnrollmentService:
    def __init__(self, enrollment_repo: EnrollmentRepository, course_repo: CourseRepository):
        ...
    async def enroll(self, learner_id: int, course_id: int) -> Enrollment: ...
    async def is_enrolled(self, learner_id: int, course_id: int) -> bool: ...