from app.repositories.lesson_progress_repository import LessonProgressRepository
from app.repositories.enrollment_repository import EnrollmentRepository
from app.models.lesson_progress import LessonProgress
class LessonProgressService:
    def __init__(self, progress_repo: LessonProgressRepository, enrollment_repo: EnrollmentRepository):
        ...
    async def mark_progress(self, learner_id: int, lesson_id: int, completed: bool) -> LessonProgress: ...
    async def get_course_completion(self, learner_id: int, course_id: int) -> dict: ...