from app.repositories.module_repository import ModuleRepository
from app.repositories.course_repository import CourseRepository
from app.schemas.module_schema import ModuleCreate, ModuleUpdate
from app.models.module import Module
class ModuleService:
    def __init__(self, module_repo: ModuleRepository, course_repo: CourseRepository):
        ...
    async def create_module(self, course_id: int, data: ModuleCreate, tutor_id: int) -> Module: ...
    async def update_module(self, module_id: int, data: ModuleUpdate, tutor_id: int) -> Module: ...
    async def delete_module(self, module_id: int, tutor_id: int) -> None: ...