"""tede_idea and trade_execution models

Revision ID: 2c070c2869b9
Revises: 6bf9ac935145
Create Date: 2026-07-18 21:04:49.615906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c070c2869b9'
down_revision: Union[str, Sequence[str], None] = '6bf9ac935145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
