"""trade_idea and trade_execution models

Revision ID: e221ffa5435c
Revises: 2c070c2869b9
Create Date: 2026-07-18 21:09:59.536959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e221ffa5435c'
down_revision: Union[str, Sequence[str], None] = '2c070c2869b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_ideas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=50), nullable=False),
    sa.Column('long_term_bias', sa.Enum('BULLISH', 'BEARISH', name='biasdirection', native_enum=False), nullable=False),
    sa.Column('trade_direction', sa.Enum('BULLISH', 'BEARISH', name='biasdirection', native_enum=False), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('screenshot_url', sa.String(length=255), nullable=True),
    sa.Column('confidence_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevel', native_enum=False), nullable=False),
    sa.Column('idea_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'MISSED', 'CANCELLED', name='ideastatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_ideas_id'), 'trade_ideas', ['id'], unique=False)
    op.create_table('trade_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_idea_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('execution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_side', sa.Enum('BUY', 'SELL', name='tradeside', native_enum=False), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('account_size', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mood', sa.Enum('CALM', 'CONFIDENT', 'DISCIPLINED', 'ANXIOUS', 'FOMO', 'GREEDY', 'FEARFUL', 'REVENGE', 'BORED', 'FRUSTRATED', 'IMPULSIVE', 'HESITANT', name='tradermood', native_enum=False), nullable=False),
    sa.Column('outcome', sa.Enum('OPEN', 'WIN', 'LOSS', 'BREAKEVEN', 'CANCELLED', 'MISSED', name='outcome', native_enum=False), nullable=False),
    sa.Column('pnl', sa.Numeric(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_idea_id'], ['trade_ideas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_executions_id'), 'trade_executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_executions_id'), table_name='trade_executions')
    op.drop_table('trade_executions')
    op.drop_index(op.f('ix_trade_ideas_id'), table_name='trade_ideas')
    op.drop_table('trade_ideas')
    # ### end Alembic commands ###
